apiVersion: v1
kind: Service
metadata:
 name: result
 labels:
  app: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 8081 #PORT ON WHICH THE SERVICE IS RUNNING 
    targetPort: 80 #PORT ON WHICH THE POD IS PRESENT
    #nodePort: 31001 #PORT ON WHICH THE NODE IS PRESENT INSIDE WHICH THE SERVICE AND PODS ARE PRESENT 
  selector:
    app: result

   
