apiVersion: v1
kind: Service
metadata:
 name: vote
 labels:
  app: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 8080 #PORT ON WHICH THE SERVICE IS RUNNING 
    targetPort: 80 #PORT ON WHICH THE POD IS PRESENT
   # nodePort: 31000 #PORT ON WHICH THE NODE IS PRESENT INSIDE WHICH THE SERVICE AND PODS ARE PRESENT 
  selector:
    app: vote

   
