apiVersion: v1
kind: Pod
metadata:
  name: result
  labels:
   app: result
spec:
  containers:
    - name: result
      image: dockersamples/examplevotingapp_result
      imagePullPolicy: IfNotPresent

      
      ports:
       - containerPort: 80
         name: result
   